[2024-03-09T17:40:39.952+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multitask_dag.taskB manual__2024-03-09T12:10:29.455972+00:00 [queued]>
[2024-03-09T17:40:39.958+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multitask_dag.taskB manual__2024-03-09T12:10:29.455972+00:00 [queued]>
[2024-03-09T17:40:39.958+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-09T17:40:39.986+0530] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): taskB> on 2024-03-09 12:10:29.455972+00:00
[2024-03-09T17:40:39.988+0530] {standard_task_runner.py:60} INFO - Started process 6540 to run task
[2024-03-09T17:40:39.991+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multitask_dag', 'taskB', 'manual__2024-03-09T12:10:29.455972+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/multitask_dag.py', '--cfg-path', '/tmp/tmpfumgicgp']
[2024-03-09T17:40:39.993+0530] {standard_task_runner.py:88} INFO - Job 58: Subtask taskB
[2024-03-09T17:40:40.043+0530] {task_command.py:423} INFO - Running <TaskInstance: multitask_dag.taskB manual__2024-03-09T12:10:29.455972+00:00 [running]> on host BreakThrough.
[2024-03-09T17:40:40.166+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='multitask_dag' AIRFLOW_CTX_TASK_ID='taskB' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T12:10:29.455972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-09T12:10:29.455972+00:00'
[2024-03-09T17:40:40.167+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-09T17:40:40.168+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Welcome to Task B\n    sleep 30\n    exit 99 //skipping the rest of the script\necho End of Task B']
[2024-03-09T17:40:40.173+0530] {subprocess.py:86} INFO - Output:
[2024-03-09T17:40:40.174+0530] {subprocess.py:93} INFO - Welcome to Task B
[2024-03-09T17:41:10.175+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 3: exit: too many arguments
[2024-03-09T17:41:10.176+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-09T17:41:10.182+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-09T17:41:10.185+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=multitask_dag, task_id=taskB, execution_date=20240309T121029, start_date=20240309T121039, end_date=20240309T121110
[2024-03-09T17:41:10.211+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 58 for task taskB (Bash command failed. The command returned a non-zero exit code 1.; 6540)
[2024-03-09T17:41:10.219+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T17:41:10.232+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
