[2024-03-09T17:45:50.168+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multitask_dag.taskC manual__2024-03-09T12:15:07.860545+00:00 [queued]>
[2024-03-09T17:45:50.174+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multitask_dag.taskC manual__2024-03-09T12:15:07.860545+00:00 [queued]>
[2024-03-09T17:45:50.174+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-09T17:45:50.203+0530] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): taskC> on 2024-03-09 12:15:07.860545+00:00
[2024-03-09T17:45:50.205+0530] {standard_task_runner.py:60} INFO - Started process 6595 to run task
[2024-03-09T17:45:50.209+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multitask_dag', 'taskC', 'manual__2024-03-09T12:15:07.860545+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/multitask_dag.py', '--cfg-path', '/tmp/tmpebl035zr']
[2024-03-09T17:45:50.210+0530] {standard_task_runner.py:88} INFO - Job 62: Subtask taskC
[2024-03-09T17:45:50.269+0530] {task_command.py:423} INFO - Running <TaskInstance: multitask_dag.taskC manual__2024-03-09T12:15:07.860545+00:00 [running]> on host BreakThrough.
[2024-03-09T17:45:50.356+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='multitask_dag' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T12:15:07.860545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-09T12:15:07.860545+00:00'
[2024-03-09T17:45:50.357+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-09T17:45:50.357+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Welcome to Task C\n    sleep 20\n    exit 130 #results the task to fail\necho End of Task C']
[2024-03-09T17:45:50.363+0530] {subprocess.py:86} INFO - Output:
[2024-03-09T17:45:50.364+0530] {subprocess.py:93} INFO - Welcome to Task C
[2024-03-09T17:46:10.366+0530] {subprocess.py:97} INFO - Command exited with return code 130
[2024-03-09T17:46:10.392+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2024-03-09T17:46:10.395+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=multitask_dag, task_id=taskC, execution_date=20240309T121507, start_date=20240309T121550, end_date=20240309T121610
[2024-03-09T17:46:10.421+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 6595)
[2024-03-09T17:46:10.445+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T17:46:10.457+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
