[2024-03-09T22:26:07.498+0530] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: sql_operator_dag.taskC manual__2024-03-09T16:56:01.849809+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
