[2024-03-13T19:59:45.237+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow_sql_operations_dag.insert_records manual__2024-03-13T14:29:34.273446+00:00 [queued]>
[2024-03-13T19:59:45.244+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow_sql_operations_dag.insert_records manual__2024-03-13T14:29:34.273446+00:00 [queued]>
[2024-03-13T19:59:45.244+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-13T19:59:45.276+0530] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): insert_records> on 2024-03-13 14:29:34.273446+00:00
[2024-03-13T19:59:45.279+0530] {standard_task_runner.py:60} INFO - Started process 292084 to run task
[2024-03-13T19:59:45.282+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'taskflow_sql_operations_dag', 'insert_records', 'manual__2024-03-13T14:29:34.273446+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/taskflow_sql_operations.py', '--cfg-path', '/tmp/tmpcdb_57ir']
[2024-03-13T19:59:45.284+0530] {standard_task_runner.py:88} INFO - Job 236: Subtask insert_records
[2024-03-13T19:59:45.362+0530] {task_command.py:423} INFO - Running <TaskInstance: taskflow_sql_operations_dag.insert_records manual__2024-03-13T14:29:34.273446+00:00 [running]> on host BreakThrough.
[2024-03-13T19:59:45.490+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='taskflow_sql_operations_dag' AIRFLOW_CTX_TASK_ID='insert_records' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T14:29:34.273446+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T14:29:34.273446+00:00'
[2024-03-13T19:59:45.519+0530] {logging_mixin.py:188} INFO - This is task C
[2024-03-13T19:59:45.650+0530] {logging_mixin.py:188} WARNING - /home/kai/airflow/dags/taskflow_sql_operations.py:50 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-03-13T19:59:45.786+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kai/airflow/dags/taskflow_sql_operations.py", line 57, in insert_records
    VALUES ('{row.name}', '{row.model}', {row.volume}, {row.weight}, {row.co2})
AttributeError: 'Pandas' object has no attribute 'name'
[2024-03-13T19:59:45.823+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=taskflow_sql_operations_dag, task_id=insert_records, execution_date=20240313T142934, start_date=20240313T142945, end_date=20240313T142945
[2024-03-13T19:59:45.879+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 236 for task insert_records ('Pandas' object has no attribute 'name'; 292084)
[2024-03-13T19:59:45.898+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-13T19:59:45.910+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
