[2024-03-09T17:29:01.875+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multitask_dag.taskA manual__2024-03-09T11:58:57.564051+00:00 [queued]>
[2024-03-09T17:29:01.881+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multitask_dag.taskA manual__2024-03-09T11:58:57.564051+00:00 [queued]>
[2024-03-09T17:29:01.881+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-09T17:29:01.909+0530] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): taskA> on 2024-03-09 11:58:57.564051+00:00
[2024-03-09T17:29:01.911+0530] {standard_task_runner.py:60} INFO - Started process 6456 to run task
[2024-03-09T17:29:01.914+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multitask_dag', 'taskA', 'manual__2024-03-09T11:58:57.564051+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/multitask_dag.py', '--cfg-path', '/tmp/tmpnboqn07v']
[2024-03-09T17:29:01.916+0530] {standard_task_runner.py:88} INFO - Job 56: Subtask taskA
[2024-03-09T17:29:01.963+0530] {task_command.py:423} INFO - Running <TaskInstance: multitask_dag.taskA manual__2024-03-09T11:58:57.564051+00:00 [running]> on host BreakThrough.
[2024-03-09T17:29:02.003+0530] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'taskA', field 'bash_command'. Template: 'taskA.sh'
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-03-09T17:29:02.004+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2357, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2907, in render_templates
    original_task.render_template_fields(context)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kai/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: taskA.sh
[2024-03-09T17:29:02.009+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=multitask_dag, task_id=taskA, execution_date=20240309T115857, start_date=20240309T115901, end_date=20240309T115902
[2024-03-09T17:29:02.033+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 56 for task taskA (taskA.sh; 6456)
[2024-03-09T17:29:02.047+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T17:29:02.070+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
