[2024-03-10T09:35:48.682+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T04:05:38.109112+00:00 [queued]>
[2024-03-10T09:35:48.688+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T04:05:38.109112+00:00 [queued]>
[2024-03-10T09:35:48.688+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-10T09:35:48.720+0530] {taskinstance.py:2214} INFO - Executing <Task(BranchPythonOperator): branch> on 2024-03-10 04:05:38.109112+00:00
[2024-03-10T09:35:48.724+0530] {standard_task_runner.py:60} INFO - Started process 122783 to run task
[2024-03-10T09:35:48.727+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_task_groups_edge_labels_dag', 'branch', 'manual__2024-03-10T04:05:38.109112+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/execute_branching_task_group_edge_labels.py', '--cfg-path', '/tmp/tmpic_pq8_0']
[2024-03-10T09:35:48.729+0530] {standard_task_runner.py:88} INFO - Job 151: Subtask branch
[2024-03-10T09:35:48.783+0530] {task_command.py:423} INFO - Running <TaskInstance: pipeline_task_groups_edge_labels_dag.branch manual__2024-03-10T04:05:38.109112+00:00 [running]> on host BreakThrough.
[2024-03-10T09:35:48.893+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='pipeline_task_groups_edge_labels_dag' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T04:05:38.109112+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T04:05:38.109112+00:00'
[2024-03-10T09:35:48.899+0530] {logging_mixin.py:188} INFO - branch
[2024-03-10T09:35:48.912+0530] {logging_mixin.py:188} INFO - filter_by_coverage
[2024-03-10T09:35:48.913+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 234, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kai/airflow/dags/execute_branching_task_group_edge_labels.py", line 36, in branch
    return filtering.taskF
AttributeError: 'TaskGroup' object has no attribute 'taskF'
[2024-03-10T09:35:48.921+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_task_groups_edge_labels_dag, task_id=branch, execution_date=20240310T040538, start_date=20240310T040548, end_date=20240310T040548
[2024-03-10T09:35:48.957+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 151 for task branch ('TaskGroup' object has no attribute 'taskF'; 122783)
[2024-03-10T09:35:48.981+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-10T09:35:49.015+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
