[2024-03-12T22:35:31.279+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow_branching_operators_dag.read_data scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-03-12T22:35:31.287+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow_branching_operators_dag.read_data scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-03-12T22:35:31.287+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-12T22:35:31.323+0530] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): read_data> on 2024-03-11 00:00:00+00:00
[2024-03-12T22:35:31.333+0530] {standard_task_runner.py:60} INFO - Started process 279439 to run task
[2024-03-12T22:35:31.391+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'taskflow_branching_operators_dag', 'read_data', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/taskflow_branching_operators_dag.py', '--cfg-path', '/tmp/tmpruqyvrdd']
[2024-03-12T22:35:31.393+0530] {standard_task_runner.py:88} INFO - Job 202: Subtask read_data
[2024-03-12T22:35:31.899+0530] {task_command.py:423} INFO - Running <TaskInstance: taskflow_branching_operators_dag.read_data scheduled__2024-03-11T00:00:00+00:00 [running]> on host BreakThrough.
[2024-03-12T22:35:32.097+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='taskflow_branching_operators_dag' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-03-12T22:35:32.104+0530] {logging_mixin.py:188} INFO - This is task A
[2024-03-12T22:35:32.118+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kai/airflow/dags/taskflow_branching_operators_dag.py", line 25, in read_data
    df=pd.read_csv('dags/datasets/data.csv')
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'dags/datasets/data.csv'
[2024-03-12T22:35:32.139+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=taskflow_branching_operators_dag, task_id=read_data, execution_date=20240311T000000, start_date=20240312T170531, end_date=20240312T170532
[2024-03-12T22:35:32.178+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 202 for task read_data ([Errno 2] No such file or directory: 'dags/datasets/data.csv'; 279439)
[2024-03-12T22:35:32.221+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T22:35:32.252+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
