[2024-03-09T17:41:11.881+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multitask_dag.taskC manual__2024-03-09T12:10:29.455972+00:00 [queued]>
[2024-03-09T17:41:11.888+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multitask_dag.taskC manual__2024-03-09T12:10:29.455972+00:00 [queued]>
[2024-03-09T17:41:11.888+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-09T17:41:11.921+0530] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): taskC> on 2024-03-09 12:10:29.455972+00:00
[2024-03-09T17:41:11.929+0530] {standard_task_runner.py:60} INFO - Started process 6544 to run task
[2024-03-09T17:41:11.938+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multitask_dag', 'taskC', 'manual__2024-03-09T12:10:29.455972+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/multitask_dag.py', '--cfg-path', '/tmp/tmp0rxy7wfr']
[2024-03-09T17:41:11.941+0530] {standard_task_runner.py:88} INFO - Job 59: Subtask taskC
[2024-03-09T17:41:11.995+0530] {task_command.py:423} INFO - Running <TaskInstance: multitask_dag.taskC manual__2024-03-09T12:10:29.455972+00:00 [running]> on host BreakThrough.
[2024-03-09T17:41:12.087+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='multitask_dag' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T12:10:29.455972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-09T12:10:29.455972+00:00'
[2024-03-09T17:41:12.090+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-09T17:41:12.092+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Welcome to Task C\n    sleep 20\n    exit 130 //results the task to fail\necho End of Task C']
[2024-03-09T17:41:12.099+0530] {subprocess.py:86} INFO - Output:
[2024-03-09T17:41:12.101+0530] {subprocess.py:93} INFO - Welcome to Task C
[2024-03-09T17:41:32.103+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 3: exit: too many arguments
[2024-03-09T17:41:32.103+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-09T17:41:32.130+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-09T17:41:32.132+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=multitask_dag, task_id=taskC, execution_date=20240309T121029, start_date=20240309T121111, end_date=20240309T121132
[2024-03-09T17:41:32.163+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task taskC (Bash command failed. The command returned a non-zero exit code 1.; 6544)
[2024-03-09T17:41:32.178+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T17:41:32.190+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
